### PR TITLE
Deleted numerous miscellaneous Bash scripts which I don't think any of the development team are using

### PR DESCRIPTION
**Pull request by bobsummerwill**
They look like they were mainly created for the purpose of creating the repositories, or for working with them "loose" which we aren't really doing anymore, or if we are, we are doing it without these scripts.
If we find that any of them are still useful then they should be readded under webthree-helpers/scripts, not in the root directory.

Also removed astyle file based on the feedback from chriseth and chfast that this style tool had not proved successful.    chfast is now experimenting with clang-format instead.

### CODE REVIEW

**Comment by bobsummerwill** [comment]
For the git commands, especially, we're better learning git and using raw commands (or IDEs).    Also, this stuff will be way simpler after the repo remerge anyway.

**Comment by chriseth** [comment]
sync.sh is the only one which is actually needed: It is run by the "update-umbrella" job. I did not want to put it inside webthree-helpers for obvious reasons.

**Comment by bobsummerwill** [comment]
Re-added sync.sh, @chriseth.   Good to go?

**Comment by bobsummerwill** [comment]
Merged.   Easy enough to re-add things if I cut too much out.

**Pull request merged**
