### PR TITLE
Fix deploy scripts.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by bobsummerwill** [comment]
LGTM.

ASIDE - Please could we move these scripts into the solidity repo itself, because that's where they're going to need to be very soon?

**Comment by chriseth** [comment]
We can move them as soon as we have solidity standalone

**Comment by bobsummerwill** [comment]
Well, what I'm saying is that moving them now will make that switch easier :-)

Maybe we add a forwarder (which will die) in the webthree-umbrella, to avoid needing to change your existing automation?   And that would drop out when we move, and the automation would happen directly on the solidity repo.

I also want them in the solidity repo so I can work through the process of consolidating your TravisCI with my TravisCI :-)

**Comment by bobsummerwill** [comment]
But actually, hmm, your TravisCI file cannot move, can it?    But the scripts can.

**Comment by chriseth** [comment]
I just made it working, let's keep it like that until we make the move.

**Pull request merged**
