### PR TITLE
Added GMP to the graph

### PR DESCRIPTION
**Pull request by bobsummerwill**
It was missing, because we only have an indirect dependency onto it, via secp256k1.

Added the three orphaned libraries into the "webthree-helper" cluster.

See new graph at https://github.com/doublethinkco/webthree-umbrella-cross/blob/gh-pages/images/dependency_graph.svg.

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Poke, poke.    Please could somebody slurp this up?   Thanks!
@subtly @LefterisJP @chriseth

**Comment by LefterisJP** [comment]
Looks good to me. @chriseth merge when you can.

@bobsummerwill Perhaps you can squash it all in one commit before? Since it's 3 commits for 1 simple thing.

**Comment by bobsummerwill** [comment]
@LefterisJP @chriseth I made a new one:
https://github.com/ethereum/webthree-umbrella/pull/116

**Comment by LefterisJP** [comment]
@bobsummerwill You don't need to delete the PR in order to squash the commits.

Simply squash the last 3 commits in your case and force push into the branch of your remote. The PR will get updated.

```
git rebase --interactive HEAD~3
# pick/squash the commits in the text editor window that opens
git push -f
```

**Comment by bobsummerwill** [comment]
Thanks for the extra git-foo.    Already made the other one now.

I will squash next time :-)

**Pull request closed without merging**
