### PR TITLE
Complete revamp of DOT dependency graph

### PR DESCRIPTION
**Pull request by anthony-cros**
This is a revamped dependency graph we have come up with at [doublethink.co](http://doublethink.co/). Here's a more [visual representation](http://imgur.com/sDCbFhp). The question marks left are components for which we are lacking information, but shouldn't be too difficult to complete on your end.

A lot of files have diverged on our fork so I went back a while and tried cherry-picking our latest commit for that file only, but somehow it only shows the one commit that "fixed the merge conflicts" (when I would have expected [this history](https://github.com/doublethinkco/webthree-umbrella/commits/e312fe8aa1f2ee0e912b2f68ac68621973ae40fd/dependency_graph.dot), to reflect @bobsummerwill's changes as well). I'm happy to redo it if anyone knows how to get around that issue!

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Woohoo!   Thanks, @anthony-cros :-)

**Comment by bobsummerwill** [comment]
And we'll keep chipping away on this as we learn more about the dependencies in the process of bringing up the cross-builds, and send further PRs as we go.

**Comment by bobsummerwill** [comment]
Please could you rename this PR to something more meaningful, @anthony-cros?    Like "Complete revamp of DOT dependency graph" ?

**Comment by LefterisJP** [comment]
I like this. The question marks are versions? Should they be version ranges or minimum versions that are known to work?

**Comment by bobsummerwill** [comment]
We should probably just strip those version suffixes from the diagram, eh, @anthony-cros?
Meta-data on versioning should live elsewhere.

**Comment by bobsummerwill** [comment]
The question marks are highlighting uncertainly about particular modules and their dependencies and usage.    The specific version numbers for external packages are the actual version numbers which are being used, though those versions might be coming from OUR specific cross-build scenario, in which case they also should be removed from this diagram.

@anthony-cros Please could you just strip the version numbers from the DOT file and update this PR?    We can leave the ? marks for nodes in the graph where there is uncertainty.     Even that is is probably of marginal value.    The whole thing needs several more passes, and preferably automated generation long-term.

More than anything, though, I would like to get this upstreamed because it is quite textually different.  We'll be iterating as we go, but the future diffs will be a lot easier to grok when we get this PR landed.

**Comment by bobsummerwill** [comment]
We are definitely missing some edges, but again, let's build those up incrementally.

**Comment by bobsummerwill** [comment]
Aha - actually the image which @anthony-cros shared higher up is out of date.

Here's what the latest version actually looks like:

https://ipfs.pics/ipfs/QmPoeqadSbjshYZeibtTgdkXAXCyvCtsrejSe8xY2hSure

**Comment by anthony-cros** [comment]
> Meta-data on versioning should live elsewhere

actually i thought it was pretty convenient to keep them here as well, since the diagram itself is necessarily redundant with the git repo. the idea would be that they would always reflect the latest commits for each submodule

**Comment by anthony-cros** [comment]
> preferably automated generation long-term.

that could be a good to keep it up-to-date, some kind of pregeneration step at build time

**Comment by anthony-cros** [comment]
> Should they be version ranges

Actually @LefterisJP , ranges are a good idea! the idea was to provided "at least one"

**Comment by bobsummerwill** [comment]
@gavofyork said ...

nice
eth & flu depend on jsconsole, which depends on jsengine.
ethminer, libwebthree, mix and aleth\* all depend on ethashseal.
pretty much everything depends on json_spirit, but it's header-only.

**Comment by bobsummerwill** [comment]
@LefterisJP, @gavofyork So nobody has answered my question yet about why we have those three orphaned copies of external libraries in webthree-helper.   Could you guys offer some insight on why these are "special"?   Thanks!

**Comment by bobsummerwill** [comment]
So what are we going to do here?
Start as-is and go from there with further PRs?
Do some minimal tidy-up with dependencies/version-tags prior to commit?
Are we generally agreed that we will merge these changes?

**Comment by bobsummerwill** [comment]
@anthony-cros I did a little more work on the DOT graph.   Please could you cherry-pick those two commits across and into this PR?   Thanks!

https://ipfs.pics/ipfs/QmP1WvYxYykanu5J5SjqYv2eJr474wdAZ7w8ctitZS7ivn

**Comment by bobsummerwill** [comment]
@anthony-cros Argh ... I have accidentally pulled the rest of the changes into the branch, and my git-foo is not sufficient for a quick fix.    I'll fix it tonight if I get a chance, or if you can, Anthony, please do.

**Comment by bobsummerwill** [comment]
@anthony-cros Please could you close this PR?    I've made a clean, new one.  https://github.com/ethereum/webthree-umbrella/pull/91   Thanks!

**Pull request closed without merging**
